// <auto-generated />
namespace Minibus.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class RouteBase_AddDayId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RouteBase_AddDayId));
        
        string IMigrationMetadata.Id
        {
            get { return "201410091419257_RouteBase_AddDayId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
