// <auto-generated />
namespace Minibus.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class RouteBase_AddDayTemplateId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RouteBase_AddDayTemplateId));
        
        string IMigrationMetadata.Id
        {
            get { return "201409130808219_RouteBase_AddDayTemplateId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
